# Generated by Django 3.2.13 on 2022-05-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_remove_schedule_date_schedule_datetime_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='repeat_weekly',
            field=models.BooleanField(default=False),
        ),
    ]
