# Generated by Django 4.0.4 on 2022-05-01 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='date',
        ),
        migrations.AddField(
            model_name='schedule',
            name='datetime_field',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='schedule',
            name='desired_lamp',
            field=models.IntegerField(choices=[(1, 'first'), (2, 'second')], default=1),
        ),
    ]
